name = "FaultTree"
uuid = "2ab4f33b-e537-4f3b-bd4c-4061373d8230"
authors = ["Hiroyuki Okamura"]
version = "0.6.0"

[deps]
DD = "dbd003b0-366b-4bd7-bab8-1704c0e14406"

[compat]
julia = "1"
DD = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
